### ISSUE TITLE
MDScrollView Resize Issue , as it shows cells above the Column & rows

### ISSUE THREAD

**Issue by ajaysharmalike** [mochidev/MDSpreadViewDemo#1]
Simply a Great Controller !!!

I have added this controller in my app and that works like a charm when . But the issue lies when I resize the controller.

I have defined the size for Spreadview in Xib as : 
x : 10 , y :65 ,width = 300 ,Height = 294.

This is the actual frame but MDSpreadView doesn't host in that frame. When I scroll, it shows an addition of one whole Row and Column behind the above the Column.

Let me know, if that can be solved as I tried it in many ways :
1) set the content offset for scrollview
2) Adding MDSpreadView into another UIView so that it can reside inside it.

For Reference : 

![ios simulator screen shot 22-aug-2013 3 16 42 pm](https://f.cloud.github.com/assets/388989/1008161/ce0de0a6-0b1b-11e3-8454-601ca65767cd.png)

Thanks,

**Comment by dimitribouniol** [comment]
This was most likely fixed in mochidev/MDSpreadView#26
